name: share_binary_example
description: "Demonstrates how to use the share_binary plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter : '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  share_binary:
    path: ../

  cupertino_icons: ^1.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
