name: share_binary
description: "This library provides the ability to use OS sharing features while handling binary files in dart code."
version: 1.1.1
homepage: https://github.com/koji-1009/share_binary

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  mime: ^1.0.0
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dr1009.app.share_binary
        pluginClass: ShareBinaryPlugin
      ios:
        pluginClass: ShareBinaryPlugin
      web:
        pluginClass: ShareBinaryWeb
        fileName: src/share_binary_web.dart
