name: share_binary
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/koji-1009/share_binary

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dr1009.app.share_binary
        pluginClass: ShareBinaryPlugin
      ios:
        pluginClass: ShareBinaryPlugin
